### PR TITLE
error: do not exit on user error

### LINKED ISSUE #1: if shim-logs fails to forward the logs to redis, process receives SIGPIPE
Related to https://github.com/threefoldtech/zos/issues/943

The redis was started with default arguments hence it doesn't allow remote client to do any write/read operations the process inside the container kept getting SIGPIPE.

restarting redis to run in (non-protected mode) the process was still not able to processed (same signal) a new container needed to be created for this to work again.

Possible solution:
If the shim can not forward the logs, it still need to read stdout/stderr ? (how to tell the user that his setup is wrong).

### PR DESCRIPTION
**Pull request by maxux**
When userland errors (like redis error, network issue, file access error, ...) happens, display an error message on stderr and does not exit with error.

When shim process exit, the whole container is stopped. An issue here should not break the whole container. A batter handling of redis reconnection could be implemented but at least now an error won't affect container live system.

The only exception is, when a memory allocation fails, process exit.
Memory allocation error usually mean something really bad on the system.

Closes #1 

This PR should be tested a little bit more before merging.

### CODE REVIEW

File: shim-logs.c [hunk 1]
```diff
@@ -93,8 +95,12 @@ int main() {
     while(1) {
         int n = epoll_wait(evfd, events, MAXEVENTS, -1);
 
-        if(n < 0)
+        if(n < 0) {
+            if(errno == EINTR)
+                continue;
```
Comment (muhamadazmy) [inline shim-logs.c:100]: Can this cause a `busy loop` if epoll_wait immediately returning errors each time it's called. may be it's better to introduce some latency before trying again.

Comment (maxux) [reply shim-logs.c:100]: `EINTR` means syscall were interrupted by a signal. This is just to avoid to exit because of a signal which was not intended to stop the whole process. It only loop on `EINTR`, other errors are handled like fatals. You should not receive lot of consecutive signals :p
